# Generated by Django 4.0.1 on 2022-02-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('cotacao', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=4)),
                ('empresa', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=150)),
                ('subsetor', models.CharField(max_length=150)),
                ('volumeMedio', models.DecimalField(decimal_places=2, max_digits=90)),
                ('valorMercado', models.DecimalField(decimal_places=2, max_digits=900)),
                ('valorFirma', models.DecimalField(decimal_places=2, max_digits=900)),
                ('ultimoBalanco', models.DateField()),
                ('numeroDeAcoes', models.DecimalField(decimal_places=0, max_digits=90)),
                ('cotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacaoEmpresa', to='infos.cotacao')),
            ],
        ),
    ]
